In [2]:
import numpy as np
import pandas
import pickle

In [3]:
with open("/home/cjchen/2020-2021/Spring2021/greco_grb/data/gbm/no_gbm_list.txt", "rb") as fp:   # Unpickling
    no_gbm_list = pickle.load(fp)

# no_gbm_list = ['GRB180205184', 'GRB180128252', 'GRB171119992', 'GRB170416583', 'GRB170203486', 'GRB170113420', 'GRB161218222', 'GRB161121186', 'GRB161020024', 'GRB160314929', 'GRB160220868', 'GRB151218857', 'GRB150917148', 'GRB150618674', 'GRB150513856', 'GRB150411026', 'GRB150326542', 'GRB150325696', 'GRB140912664', 'GRB140825980', 'GRB140711691', 'GRB140628704', 'GRB140501139', 'GRB140219319', 'GRB140115899', 'GRB140109877', 'GRB131029990', 'GRB130925164', 'GRB130909817', 'GRB130908677', 'GRB120817168', 'GRB120624309', 'GRB120513531']

In [4]:
grbweb = pandas.read_pickle("/home/cjchen/2020-2021/Spring2021/greco_grb/data/grbweb/grb_grbweb.pkl")
grbweb.head()

,grb_name,grb_name_GBM,ra,dec,mjd_start,t100,t90,gbm,source_uncertainty,redshift,t_center
0,GRB190613B,GRB190613449,305.431917,-4.646667,58647.449285,0.001905,0.000056,0,0.000056,NaN,58647.450238
1,GRB190613A,GRB190613172,182.529208,67.235278,58647.171736,0.000204,0.000198,0,0.000056,NaN,58647.171838
2,GRB190612A,GRB190612165,223.950000,62.100000,58646.164836,0.001677,0.001677,1,7.025096,NaN,58646.165675
3,GRB190611B,GRB190611950,84.758333,50.833333,58645.949833,0.001217,0.001164,0,5.900000,NaN,58645.950442
4,GRB190611A,None,324.722625,-56.074278,58645.742373,0.000484,0.000484,0,0.000194,NaN,58645.742615

In [11]:
no_gbm_df = grbweb[grbweb['grb_name_GBM'].isin(no_gbm_list)]
no_gbm_df.head()

,grb_name,grb_name_GBM,ra,dec,mjd_start,t100,t90,gbm,source_uncertainty,redshift,t_center
396,GRB180205A,GRB180205184,126.819750,11.541917,58154.184301,0.000245,0.000178,0,0.000054,1.409,58154.184424
404,GRB180128B,GRB180128252,71.280000,-9.040000,58146.252346,0.000456,0.000450,1,NaN,NaN,58146.252574
458,GRB171119A,GRB171119992,135.316667,-50.283333,58076.991966,0.000330,0.000305,0,4.166667,NaN,58076.992131
635,GRB170416A,GRB170416583,284.220000,-57.020000,57859.583342,0.000717,0.000717,1,NaN,NaN,57859.583700
690,GRB170203B,GRB170203486,245.090000,-0.510000,57787.486410,0.000004,0.000004,1,NaN,NaN,57787.486412

In [12]:
print("NaN, well, poor")
np.sum(np.isnan(no_gbm_df.source_uncertainty)), np.sum(no_gbm_df.source_uncertainty < 1), np.sum(no_gbm_df.source_uncertainty >= 1)

NaN, well, poor

(25, 7, 1)